server:
  port: 8061

spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.101.163.223:3306/zydc?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
  redis:
    database: 0
    host: 39.101.163.223         # Redis服务器地址
    port: 6379              # Redis服务器连接端口
    password:               # Redis服务器连接密码（默认为空）

  thymeleaf:
    #缓冲的配置
    cache: false
    check-template: true
    check-template-location: true
    #开启MVC thymeleaf 视图解析
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**

#  #给项目来个名字
#  application:
#    name: rabbitmq-zydcAuction
#  #配置rabbitMq 服务器
#  rabbitmq:
#    host: 42.192.42.75
#    port: 5672
#    username: guest
#    password: guest
#    #虚拟host 可以不设置,使用server默认host
#    virtual-host: zydcAuction



#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.drjy.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
